---
# tasks file for iptables
- name: Install iptables-persistent
  apt: 
    name: 
      - iptables-persistent
    state: present

- name: Set up iptables rules
  template: src=rules.v4.j2 dest=/etc/iptables/rules.v4
  notify: 
    - iptables-restore

- name: Set up ip6tables rules
  template: src=rules.v6.j2 dest=/etc/iptables/rules.v6
  notify: 
    - ip6tables-restore
